---
- hosts: all
  become: yes
  tasks:
  - name: download
    get_url: 
      url: https://www.dropbox.com/download?dl=packages/fedora/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm 
      dest: /tmp
  - name: install
    dnf:
      name: /tmp/nautilus-dropbox-2015.10.28-1.fedora.x86_64.rpm 
